from enum import Enum

# //IMPLEMENTACION DEL CASO DE ENUMERACION

class Mes(Enum):
    ENERO = "ENERO"
    FEBRERO ="FEBRERO"
    MARZO = "MARZO"
    ABRIL = "ABRIL"
    MAYO = "MAYO"
    JUNIO = "JUNIO"
    JULIO = "JULIO"
    AGOSTO = "AGOSTO"
    SEPTIEMBRE = "SEPTIEMBRE"
    OCTUBRE = "OCTUBRE"
    NOVIEMBRE = "NOVIMEBRE"
    DICIEMBRE = "DICIEMBRE"