package gestorAplicacion.servicio;

//IMPLEMENTACION DEL CASO DE ENUMERACION

public enum Mes{
    ENERO, FEBRERO, MARZO, ABRIL, MAYO, JUNIO, JULIO, AGOSTO, SEPRTIEMBRE, OCTUBRE, NOVIEMBRE, DICIEMBRE;
}
